---
- import_tasks: "deploy_networkd_interfaces.d/deploy_networkd_interfaces_prereq.yml"
- import_tasks: "deploy_networkd_interfaces.d/deploy_networkd_interfaces_generic.yml"
- import_tasks: "deploy_networkd_interfaces.d/deploy_networkd_interfaces_vlan.yml"
- import_tasks: "deploy_networkd_interfaces.d/deploy_networkd_interfaces_macvlan.yml"
- include_tasks: "deploy_networkd_interfaces.d/deploy_networkd_interfaces_vlan_macvlan.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_networkd'] |
    community.general.json_query(\"[].interfaces[?interface=='\" ~
    vars['outer_item'] ~ \"'].vlans[]\") | flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item_vlan"
    label: "{{ 'Try to deploy macvlans on vlan interface: ' ~
      outer_item_vlan['name'] }}"
  when:
  - "outer_item_vlan['macvlans'] is defined"
  - "outer_item_vlan['macvlans'] != []"
