---
- name: systemd_helper | Deploy networkd.conf
  template:
    src: "systemd_networkd.j2"
    dest: "/etc/systemd/networkd.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
  - "Restart systemd-networkd"
- name: systemd_helper | Enable systemd-networkd service
  systemd:
    name: "systemd-networkd"
    enabled: "yes"
  when:
  - "hostvars[inventory_hostname]['systemd_networkd'] |
     community.general.json_query(vars['systemd_networkd_enable']) is defined"
  - "hostvars[inventory_hostname]['systemd_networkd'] |
     community.general.json_query(vars['systemd_networkd_enable']) == 'true'"
  vars:
    systemd_networkd_enable: "[] | map(&enable || 'false', @) | [0]"
