---
- ansible.builtin.include_tasks:
    file: "deploy_networkd_interfaces.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_networkd_interfaces'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
- name: systemd_helper | Enable systemd-networkd service
  ansible.builtin.systemd:
    name: "systemd-networkd"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['systemd_networkd'] |
       community.general.json_query(vars['systemd_networkd_enable']) is defined"
    - "hostvars[inventory_hostname]['systemd_networkd'] |
       community.general.json_query(vars['systemd_networkd_enable']) == 'true'"
  vars:
    systemd_networkd_enable: "[] | map(&enable || 'false', @) | [0]"
