---
- name: "systemd_helper | Deploy sysusers"
  ansible.builtin.template:
    src: "systemd_sysusers.j2"
    dest: "{{ '/etc/sysusers.d/' ~ vars['outer_item'] ~ '.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  loop: "{{ hostvars[inventory_hostname]['systemd_sysusers'] |
    community.general.json_query(\"[].create[?file_name=='\" +
    vars['outer_item'] + \"']\") | flatten(levels=1) }}"
  loop_control:
    label: "{{ item['file_name'] }}"
