---
- name: "systemd_helper | Deploy tmpfiles"
  ansible.builtin.template:
    src: "systemd_tmpfiles.j2"
    dest: "{{ '/etc/tmpfiles.d/' ~ vars['outer_item'] ~ '.conf' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
    validate: "{{ 'systemd-tmpfiles --' + vars['query_type'] + ' %s' }}"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] |
    community.general.json_query(\"[].\" + vars['query_type'] +
    \"[?file_name=='\" + vars['outer_item'] + \"']\") | flatten(levels=1) }}"
  loop_control:
    label: "{{ item['file_name'] }}"
  register: "systemd_tmpfiles_deploy_result"
- name: "systemd_helper | Touch /usr for systemd-update-done service"
  ansible.builtin.file:
    path: "/usr"
    state: "touch"
    mode: "0755"
  when:
    - "vars['systemd_tmpfiles_deploy_result'] is changed"
    - "vars['systemd_tmpfiles_deploy_result'] is success"
  diff: false
