---
- name: "systemd_helper | Deploy logind.conf"
  ansible.builtin.template:
    src: "systemd_logind.j2"
    dest: "/etc/systemd/logind.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart systemd-logind"
