---
- name: "systemd_helper | Include systemd-modules-load deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_modules_load.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_modules_load_create'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
