---
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [create]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_create'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when: "vars['systemd_tmpfiles_create'] is defined"
  vars:
    query_type: "create"
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [clean]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_clean'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when: "vars['systemd_tmpfiles_clean'] is defined"
  vars:
    query_type: "clean"
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [remove]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_remove'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  when: "vars['systemd_tmpfiles_remove'] is defined"
  vars:
    query_type: "remove"
