---
- name: "systemd_helper | Include systemd-udev deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_udev.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_udev_rules'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
