---
- name: "systemd_helper | Set facts about logind"
  ansible.builtin.set_fact:
    systemd_logind_logind: "{{ hostvars[inventory_hostname]['systemd_logind'] |
      community.general.json_query('[]') }}"
